webProje/Controllers/BisikletController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using webProje.Data;
using webProje.Models;

namespace webProje.Controllers
{
    public class BisikletController : Controller
    {
        private readonly ApplicationDbContext dbBisiklet;

        public BisikletController(ApplicationDbContext context)
        {
            dbBisiklet = context;
        }


        public IActionResult Index()
        {
            List<Bisiklet> bisikletListe = dbBisiklet.Bisikletler.ToList();

            ViewModel viewModel = new ViewModel();
            ViewModel vm = viewModel;
            vm.BisikletVM = bisikletListe.ToList();

            return View(vm);
        }

        public IActionResult KadroBoyu()
        {
            return View();
        }

        public IActionResult DagBisikletleri()
        {
            List<Bisiklet> bisikletListe = dbBisiklet.Bisikletler.Where(
                dbBisiklet => dbBisiklet.KullanimAlani.Contains("dag")).ToList();

            var favoriler = dbBisiklet.KullaniciFavorileri.ToList();

            ViewModel viewModel = new ViewModel();
            ViewModel vm = viewModel;
            vm.BisikletVM = bisikletListe.ToList();
            return View(vm);
        }

        public IActionResult YolBisikletleri()
        {
            List<Bisiklet> bisikletListe = dbBisiklet.Bisikletler.Where(
                dbBisiklet => dbBisiklet.KullanimAlani.Contains("yol")).ToList();

            ViewModel viewModel = new ViewModel();
            ViewModel vm = viewModel;
            vm.BisikletVM = bisikletListe.ToList();

            return View(vm);
        }

        public IActionResult SehirBisikletleri()
        {
            List<Bisiklet> bisikletListe = dbBisiklet.Bisikletler.Where(
                dbBisiklet => dbBisiklet.KullanimAlani.Contains("sehir")).ToList();

            ViewModel viewModel = new ViewModel();
            ViewModel vm = viewModel;
            vm.BisikletVM = bisikletListe.ToList();

            return View(vm);
        }

        public IActionResult Favoriler()
        {
            var bisikletListe = dbBisiklet.KullaniciFavorileri.ToList();

            ViewModel viewModel = new ViewModel();
            ViewModel vm = viewModel;
            vm.KullaniciFavoriVM = bisikletListe.ToList();
            return View(vm);
        }
        public IActionResult Karsilastir()
        {
            var bisikletListe = dbBisiklet.Karsilastirmalar.ToList();
            ViewModel viewModel = new ViewModel();
            ViewModel vm = viewModel;
            vm.KarsilastirmaVM = bisikletListe.ToList();
            return View(vm);
        }
        public IActionResult KarsilastirmayaEkle()
        {
            return View();
        }
        [HttpPost]
        public IActionResult KarsilastirmayaEkle([Bind("KullaniciIp", "BisikletId", "Marka", "Model", "Materyal", "JantCapi", "VitesSayisi", "KullanimAlani", "FrenTuru", "SuspansiyonTuru")] Karsilastirma a)
        {
            dbBisiklet.Add(a);
            dbBisiklet.SaveChanges();
            return RedirectToAction("Karsilastir");
        }

        public IActionResult FavorilereEkle()
        {
            return View();
        }
        [HttpPost]
        public IActionResult FavorilereEkle([Bind("KullaniciId", "BisikletId", "KullanimAlani", "Marka", "Model")] KullaniciFavori a)
        {
            dbBisiklet.Add(a);
            dbBisiklet.SaveChanges();
            return RedirectToAction("Favoriler");
        }

        public IActionResult FavoriCikar()
        {
            return View();
        }
        [HttpPost]
        public IActionResult FavoriCikar(KullaniciFavori fav)
        {
            var dbFav = dbBisiklet.KullaniciFavorileri.Find(fav.FavId);
            dbBisiklet.KullaniciFavorileri.Remove(dbFav);
            dbBisiklet.SaveChanges();
            return RedirectToAction("Favoriler");
        }

        public IActionResult KarsCikar()
        {
            return View();
        }
        [HttpPost]
        public IActionResult KarsCikar(Karsilastirma kars)
        {
            var dbKars = dbBisiklet.Karsilastirmalar.Find(kars.KarsId);
            dbBisiklet.Karsilastirmalar.Remove(dbKars);
            dbBisiklet.SaveChanges();
            return RedirectToAction("Karsilastir");
        }
    }
}

webProje/Views/Shared/_Culture.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var culture = Context.Features.Get<IRequestCultureFeature>();
    var cultureList = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<div>
    <form asp-controller="Home" asp-action="CultureManagement"
          asp-route-returnUrl="@returnUrl" method="post">
        <label class="mr-sm-2 sr-only" for="inlineFormCustomSelect">Preference</label>

        <select class="custom-select mr-sm-2 text-danger" id="inlineFormCustomSelect" style="border:none; background-color:#470422" name="culture" asp-for="@culture.RequestCulture.UICulture.Name" asp-items="cultureList"
                onchange="this.form.submit();">
        </select>
    </form>
</div>

webProje/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BisikletiniBul</title>
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/site.css" />


    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

</head>
<body style="background-color: #3b1d09" > 

    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@localizer["anasayfa"]</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial" />
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @localizer["bis"]
                        </a>
                        <div class="dropdown-menu" style="background-color: #470520" aria-labelledby="navbarDropdownMenuLink">
                            <a class="nav-link" asp-area="" asp-controller="Bisiklet" asp-action="Index">@localizer["tbis"]</a>
                            <a class="nav-link" asp-area="" asp-controller="Bisiklet" asp-action="DagBisikletleri">@localizer["dagbis"]</a>
                            <a class="nav-link" asp-area="" asp-controller="Bisiklet" asp-action="YolBisikletleri">@localizer["yolbis"]</a>
                            <a class="nav-link" asp-area="" asp-controller="Bisiklet" asp-action="SehirBisikletleri">@localizer["sehirbis"]</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Bisiklet" asp-action="Karsilastir">@localizer["karsilastirma"]</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Bisiklet" asp-action="Favoriler">@localizer["favoriler"]</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Bisiklet" asp-action="KadroBoyu">@localizer["kadroboyu"]</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <header class="masthead text-center text-white">
        <div class="masthead-content">
            <div class="container" >
                <main role="main">
                    @RenderBody()
                </main>
            </div>
        </div>
    </header>

    <footer class="border-top footer text-muted">
        <div class="container">
            <p class="m-0 text-center text-white small">&copy; 2021 - BisikletiniBul - <a class="text-danger" asp-area="" asp-controller="Home" asp-action="Privacy">@localizer["gizlilik"]</a></p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>